FROM node:current-alpine

RUN npm install -g npm@latest

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json .

# Install dependencies
RUN npm install 
#--omit=dev

# Copy the frontend source code to the container
COPY . .

# Command to run the application
CMD ["npm", "run", "start"]