services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        environment:
            - REACT_APP_PORT=${REACT_APP_PORT}
        ports:
            - ${REACT_APP_PORT}:${REACT_APP_PORT}
        networks:
            - net
        volumes:
            - ./downloads:/app/downloads:ro

networks:
    net:
        driver: bridge
